import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../src/store.mjs';
import {handleReply,prepareChoiceButtons} from '../src/dialog.mjs';
import {matchPayment,formatMatches} from '../src/matching.mjs';
import {prepareAutomatic} from '../src/automatic.mjs';
import {writeFileSync} from 'node:fs';
const config={crmWrites:true,invoiceAllowlist:[],automatic:{enabled:true,scope:'recipient_companies',fromEventId:1,fromDate:'2026-09-18'},recipientCompanyIds:[2281,2285],teamDialog:'chat1',uploadUsers:[49]};
const payment={payerName:'ООО Тест',amountCents:10000,currency:'RUB',direction:'incoming',status:'credited',bankReference:'100',date:'2026-09-22',purpose:'Счет № 51'};
const invoice={id:10,categoryId:31,stageId:'DT1078_31:CLIENT',companyId:100,mycompanyId:2285,currencyId:'RUB',ufCrm23_1768411333:'ООО Тест',ufCrm23_1768411703:'51',ufCrm23_1770923673:'100|RUB'};
const otherInvoice={...invoice,id:11,companyId:101,ufCrm23_1768411333:'ООО Второй клиент'};
const otherPayment={...payment,payerName:'ООО Второй клиент',bankReference:'101'};
const vibe={read:async id=>id===11?otherInvoice:invoice,request:async path=>path.includes('/users')?{data:[{id:49,active:true},{id:83,active:true}]}:{data:{title:'ООО ДЕМО ПОЛУЧАТЕЛЬ'}}};
const job={id:'7',body:JSON.stringify({date:'2026-09-22'})},context={dialog:'chat1',author:49};
test('multiple payment buttons, recipient conflict and confirmation status',async()=>{
const result={};
const store=new Store(':memory:');
const payments=[payment,otherPayment].map(p=>({...p,bankReference:null})),matches=payments.map(p=>matchPayment(p,[invoice,otherInvoice]));
result.multiCandidates=matches.map(x=>x.candidates.map(c=>({id:c.id,number:c.number,legalName:c.legalName})));
result.multiAuto=await prepareAutomatic({config,store,vibe},job,context,payments,matches);
result.multiButtons=prepareChoiceButtons(store,job,context,payments,matches)??null;
store.ingest({events:[{eventId:7,data:{message:{authorId:49},chat:{dialogId:'chat1'}}}],nextOffset:8});
store.db.prepare('INSERT INTO extracted VALUES(?,?,?)').run('7',1,JSON.stringify({payments}));
store.db.prepare('INSERT INTO matches VALUES(?,?)').run('7',JSON.stringify({matches}));
store.db.prepare('INSERT INTO inbox(id,body) VALUES(?,?)').run('8','{}');
await handleReply(store,vibe,{id:'8'},{...context,author:83,text:'счет 51'},config);
result.multiReply=store.db.prepare("SELECT text,keyboard FROM outbox WHERE event_id='8'").get();
result.multiStates=store.db.prepare('SELECT state FROM payment_dialogs').all();
const conflict={...payment,recipientName:'ООО Другая организация'};
const store2=new Store(':memory:');
const matched=matchPayment(conflict,[invoice]);
result.conflictAuto=await prepareAutomatic({config,store:store2,vibe},job,context,[conflict],[matched]);
result.conflictText=formatMatches([matched],config);
result.conflictButtons=prepareChoiceButtons(store2,job,context,[conflict],[matched])??null;
const store3=new Store(':memory:');
const ambiguous=[matchPayment({...payment,purpose:''},[invoice,{...invoice,id:12}])];
const keys=prepareChoiceButtons(store3,job,context,[{...payment,purpose:''}],ambiguous);
const send=async(id,text)=>{store3.db.prepare('INSERT INTO inbox(id,body) VALUES(?,?)').run(id,'{}');await handleReply(store3,vibe,{id},{...context,author:83,text},config);return store3.db.prepare('SELECT text,keyboard FROM outbox WHERE event_id=?').get(id);};
const selected=await send('8','Выбрать счет '+keys[0].COMMAND_PARAMS);
await send('9','Подтвердить выбор '+JSON.parse(selected.keyboard)[0].COMMAND_PARAMS);
result.groupConfirmState=store3.db.prepare('SELECT state FROM payment_dialogs').get().state;
result.reviewReadyStatus=(await send('10','да')).text;
result.selectionLink=selected.text.includes('/details/10/');

assert.equal(result.multiAuto,false);
assert.equal(result.multiButtons.length,2);
assert.notEqual(result.multiButtons[0].COMMAND_PARAMS,result.multiButtons[1].COMMAND_PARAMS);
const sendMulti=async(id,text)=>{store.db.prepare('INSERT INTO inbox(id,body) VALUES(?,?)').run(id,'{}');await handleReply(store,vibe,{id},{...context,author:83,text},config);return store.db.prepare('SELECT text,keyboard FROM outbox WHERE event_id=?').get(id);};
for(const [i,key] of result.multiButtons.entries()){
 const selected=await sendMulti(String(9+i*2),'Выбрать счет '+key.COMMAND_PARAMS);
 assert.ok(selected.text.includes('/details/'+(10+i)+'/'));
 await sendMulti(String(10+i*2),'Подтвердить выбор '+JSON.parse(selected.keyboard)[0].COMMAND_PARAMS);
}
assert.deepEqual(store.db.prepare('SELECT state FROM payment_dialogs').all().map(r=>r.state),['review_ready','review_ready']);
assert.equal(result.conflictAuto,false);
assert.match(result.conflictText,/получател/i);
assert.doesNotMatch(result.conflictText,/запись для этого счета пока не включена/);
assert.equal(result.conflictButtons.length,1);
assert.match(result.reviewReadyStatus,/ожидает обработки/);
assert.doesNotMatch(result.reviewReadyStatus,/выключена/);
config.crmWrites=false;
assert.match((await send('11','да')).text,/выключена/);
config.crmWrites=true;
const noRef={...payment,bankReference:null},noRefMatch=matchPayment(noRef,[invoice]);
assert.equal(await prepareAutomatic({config,store:store2,vibe}, {...job,id:'12'},context,[noRef],[noRefMatch]),false);
assert.equal(noRefMatch.review.code,'MISSING_BANK_REFERENCE');
assert.equal(prepareChoiceButtons(store2,{id:'12'},context,[noRef],[noRefMatch]).length,1);
assert.equal(noRefMatch.review.allowPayment,true);
store.close();store2.close();store3.close();
});
